server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /_next/static/ {
        try_files $uri =404;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ $uri.html =404;
    }

    error_page 404 /404.html;

    location = /404.html {
        internal;
    }
}
